### ISSUE TITLE
Test before release 3.5.0

### ISSUE THREAD

**Issue by skyghis** [skyghis/j-interop-ng#18]
Hello @pgharron,

Can you please test current main branch `jcifs-ng` before I release a new version ?
If everything is OK for you, I can create and deploy a new version.

**Comment by pgharron** [comment]
Hi @skyghis, thank you.   Do you have any guidance on how the tests are supposed to be ran, and what needs to be running on the server that the tests will connect to?  For example, does the server need to be a particular version of Windows?

I have tested locally for the DCOM Server that I need to connect to.

**Comment by skyghis** [comment]
I no longer use this library, so test what you need :smile:

If anybody need another fix, a new issue can be done later.

**Comment by pgharron** [comment]
OK :smile: thank you!

**Comment by pgharron** [comment]
Hi @skyghis , OK I have tested as much as I can.  

Please press the button when convenient! :pray:

**Comment by skyghis** [comment]
Release done, should be available on Maven central soon.

**Comment by pgharron** [comment]
> Release done, should be available on Maven central soon.

Thanks very much!
